apiVersion: apps/v1
kind: Deployment
metadata:
  name: quinteros-bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quinteros-bank
  template:
    metadata:
      labels:
        app: quinteros-bank
    spec:
      containers:
        - name: quinteros-bank
          image: quinterosbank.azurecr.io/quinteros-bank-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: JDBC_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: quinteros-bank-secret
                  key: JDBC_DATABASE_URL

            - name: JDBC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: quinteros-bank-secret
                  key: JDBC_DATABASE_USERNAME

            - name: JDBC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quinteros-bank-secret
                  key: JDBC_DATABASE_PASSWORD

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: quinteros-bank-secret
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: quinteros-bank-secret
                  key: GOOGLE_CLIENT_SECRET

            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: quinteros-bank-secret
                  key: GITHUB_CLIENT_ID

            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: quinteros-bank-secret
                  key: GITHUB_CLIENT_SECRET

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: quinteros-bank-secret
                  key: JWT_SECRET
